"""change is_read to boolean

Revision ID: 9deb043653c2
Revises: a81bca768546
Create Date: 2026-06-26 14:10:51.961690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9deb043653c2'
down_revision: Union[str, Sequence[str], None] = 'a81bca768546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.alter_column('messages', 'is_read',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('offers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('offers', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offers', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('offers', 'updated_at')
    op.alter_column('messages', 'is_read',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    # ### end Alembic commands ###
